# Generated by Django 4.2.15 on 2024-08-20 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("companyApp", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="GenerateInfo", new_name="GeneralInfo",),
    ]
