# Generated by Django 4.2.15 on 2024-08-20 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companyApp", "0002_rename_generateinfo_generalinfo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("icon", models.CharField(blank=True, max_length=50, null=True)),
                ("title", models.CharField(max_length=355, unique=True)),
                ("description", models.TextField()),
            ],
        ),
    ]
