# Generated by Django 4.2.15 on 2024-08-21 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("companyApp", "0004_testimonial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="testimonial", old_name="rating", new_name="rating_count",
        ),
    ]
