# Generated by Django 4.2.15 on 2024-08-21 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companyApp", "0005_rename_rating_testimonial_rating_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testimonial",
            name="rating_count",
            field=models.IntegerField(
                choices=[(1, "One"), (2, "Two"), (3, "Three"), (4, "Four"), (5, "Five")]
            ),
        ),
    ]
