# Generated by Django 4.2.15 on 2024-08-22 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companyApp", "0006_alter_testimonial_rating_count"),
    ]

    operations = [
        migrations.CreateModel(
            name="FrequentlyAskedQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=300)),
            ],
        ),
    ]
