# Generated by Django 4.2.15 on 2024-08-22 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companyApp", "0007_frequentlyaskedquestion"),
    ]

    operations = [
        migrations.AddField(
            model_name="frequentlyaskedquestion",
            name="answer",
            field=models.TextField(default="add"),
        ),
    ]
