# Generated by Django 4.2.15 on 2024-08-23 14:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companyApp", "0010_alter_contactformlog_sent_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("blog_image", models.CharField(blank=True, max_length=225, null=True)),
                ("category", models.CharField(blank=True, max_length=50, null=True)),
                ("title", models.CharField(max_length=50)),
                ("author", models.CharField(max_length=50)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2024,
                            8,
                            23,
                            14,
                            19,
                            42,
                            701786,
                            tzinfo=datetime.timezone.utc,
                        )
                    ),
                ),
                ("content", models.TextField()),
            ],
        ),
    ]
