# Generated by Django 4.2.15 on 2024-08-23 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companyApp", "0011_blog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
