# Generated by Django 4.2.15 on 2024-08-23 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companyApp", "0012_alter_blog_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog", name="title", field=models.CharField(max_length=100),
        ),
    ]
