# Generated by Django 4.2.15 on 2024-08-23 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("companyApp", "0014_author_alter_blog_author"),
    ]

    operations = [
        migrations.RemoveField(model_name="blog", name="author",),
    ]
