# Generated by Django 4.2.15 on 2024-08-24 10:49

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("companyApp", "0018_blog_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog", name="content", field=ckeditor.fields.RichTextField(),
        ),
    ]
